## finally block raised exception and handled


try:

        print('try')

        print(10/0)

except ZeroDivisionError:

        print('except')

finally:

        print('finally')



### o/p:

        try
        except
        finally
